<?php defined('ARI_FRAMEWORK_LOADED') or die('Direct Access to this location is not allowed.'); AriKernel::import('File.FileManager'); class AriJoomlaHelper extends AriObject { function deletePlugin($name, $type = 'content') {
global $database, $mosConfig_absolute_path; $table = AriJoomlaBridge::isJoomla1_5() ? '#__plugins' : '#__mambots'; $query = sprintf('DELETE FROM %s WHERE `element` = %s AND folder = %s', $table, $database->Quote($name), $database->Quote($type));
$database->setQuery($query); $database->query(); if ($database->getErrorNum()) { return false; } return true; } function deleteModule($name, $type = 'content') { global $database, $mosConfig_absolute_path;
$query = sprintf('DELETE FROM #__modules WHERE `module` = %s', $database->Quote($name)); $database->setQuery($query); $database->query(); if ($database->getErrorNum()) { return false; } $ret = true; if (AriJoomlaBridge::isJoomla1_5()) {
$moduleDir = AriFileManager::ensureEndWithSlash($mosConfig_absolute_path) . '/modules/' . $name . '/'; AriFileManager::deleteFiles($moduleDir); } return $ret; } function isPluginInstalled($name, $type = 'content') {
global $database, $mosConfig_absolute_path; $table = AriJoomlaBridge::isJoomla1_5() ? '#__plugins' : '#__mambots'; $query = sprintf('SELECT COUNT(*) FROM %s WHERE `element` = %s AND folder = %s', $table, $database->Quote($name),
$database->Quote($type)); $database->setQuery($query); $cnt = $database->loadResult(); if (empty($cnt)) return false; $pluginDir = AriJoomlaBridge::isJoomla1_5() ? 'plugins' : 'mambots';
$pluginPath = AriFileManager::ensureEndWithSlash($mosConfig_absolute_path) . $pluginDir . '/' . $type . '/' . $name . '.php'; return @file_exists($pluginPath); } function isModuleInstalled($name) { global $database, $mosConfig_absolute_path;
$query = sprintf('SELECT COUNT(*) FROM #__modules WHERE `module` = %s', $database->Quote($name)); $database->setQuery($query); $cnt = $database->loadResult(); if (empty($cnt)) return false;
$modulePath = AriFileManager::ensureEndWithSlash($mosConfig_absolute_path) . 'modules/'; if (AriJoomlaBridge::isJoomla1_5()) { $modulePath .= $name . '/'; } $modulePath .= $name . '.php'; return @file_exists($modulePath); }
function isRequireFtp() { if (!AriJoomlaBridge::isJoomla1_5()) return false; jimport('joomla.client.helper'); return !JClientHelper::hasCredentials('ftp'); } } ?>